### Create
POST localhost:8080/api/v1/users
Content-Type: application/json

{
  "name": "John",
  "lastName": "Doe",
  "email": "john@email.com",
  "password": "123456"
}

### Get All
GET localhost:8080/api/v1/users

### Get By Id
GET localhost:8080/api/v1/users/ef4e729b-6bf9-4c82-b51f-b902c94d5a8b

### Search
GET localhost:8080/api/v1/users/search?q=ja

### Update
PATCH localhost:8080/api/v1/users/ef4e729b-6bf9-4c82-b51f-b902c94d5a8b
Content-Type: application/json

{
  "name": "Aquel",
  "lastname": "doggy",
  "email": "wolfman@email.com"
}

### Delete
DELETE localhost:8080/api/v1/users/ef4e729b-6bf9-4c82-b51f-b902c94d5a4b